version: '3.1'

services:

  wordpress:
    image: wordpress
    restart: always
    ports:
            - "${ppg_port}:80"

    volumes:
      - ./wp:/var/www/html
    environment:
      - WORDPRESS_DB_PASSWORD= ${wp_pwd} 
      - VIRTUAL_HOST=pingouinpowagaming.net

  mysql:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${mysqlrootpwd}
